name: Install Deps Debian

description: Install build and test dependencies on Debian-based systems

runs:
  using: composite
  steps:
    - run: |
        sudo apt-get --allow-releaseinfo-change update
        sudo apt-get -y -f install \
          build-essential \
          ninja-build \
          cmake \
          lua5.1 \
          luarocks \
          lcov \
          ruby-dev \
          liblz4-dev \
          autoconf \
          automake \
          libtool \
          snap snapd

        sudo luarocks install luacheck 0.26.1
        sudo gem install coveralls-lcov
        sudo snap install powershell --classic
      shell: bash
