name: integration

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]
  workflow_dispatch:

concurrency:
  # Update of a developer branch cancels the previously scheduled workflow
  # run for this branch. However, the 'master' branch, release branch, and
  # tag workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow run ID' +
  # 'workflow run attempt' because it is a unique combination for any run.
  # So it effectively discards grouping.
  #
  # Important: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push event.
  group: ${{ (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/heads/release/') ||
    startsWith(github.ref, 'refs/tags/')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  tarantool:
    # Run on push to the 'master' and release branches of tarantool/tarantool
    # or on pull request if the 'full-ci' or 'integration-ci' label is set.
    if: github.repository == 'tarantool/tarantool' &&
        ( github.event_name != 'pull_request' ||
          contains(github.event.pull_request.labels.*.name, 'full-ci') ||
          contains(github.event.pull_request.labels.*.name, 'integration-ci') )

    uses: tarantool/tarantool/.github/workflows/reusable_build.yml@master
    with:
      ref: ${{ github.sha }}
      os: ubuntu
      dist: focal

  php-client:
    needs: tarantool
    uses: ylobankov/tarantool-php-client/.github/workflows/reusable_qa.yml@bump-action-versions
    with:
      artifact_name: tarantool-ubuntu-focal-${{ github.sha }}
